language: node_js
cache: yarn
node_js:
  - "11"
  - "10"
  - "8"
# script: yarn run test:CI
after_success:
  # Send coverage data to coveralls.
  # - yarn run test:cover:CI
  npm run build

deploy:
  provider: surge
  project: ./dist
  domain: cs98-duet.surge.sh