language: node_js
cache: yarn
node_js:
  - "11"
  # - "10"
  # - "8"
script: 
  - npm run build:CI
after_success:
  # Send coverage data to coveralls.
  # - yarn run test:cover:CI

env:
  global:
    - AUTH_SERVER_URL="https://cs98-duet-auth-server.herokuapp.com/login"

deploy:
  skip_cleanup: true
  provider: surge
  login: SURGE_LOGIN
  token: SURGE_TOKEN
  project: ./dist/
  domain: cs98-duet.surge.sh