
export const FETCH_USER_SPOTIFY_PROFILE = "FETCH_USER_SPOTIFY_PROFILE";
export const FETCH_USER_FRIENDS = "FETCH_USER_FRIENDS";
export const FETCH_USER_TASTE = "FETCH_USER_TASTE";
export const FETCH_TRACK_INFOS = "FETCH_TRACK_INFOS";
export const FETCH_TOP_GENRES = "FETCH_TOP_GENRES";
export const FETCH_DECADE = "FETCH_DECADE";
export const FETCH_TRENDEX = "FETCH_TRENDEX";
export const FETCH_TOKEN = "FETCH_TOKEN";
export const FETCH_FRIEND = "FETCH_FRIEND";
export const CLEAR_FRIEND = "CLEAR_FRIEND";
export const STORE_USER = "STORE_USER";
export const ADD_FRIEND = "ADD_FRIEND";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const CLEAR_USER = "CLEAR_USER";
