
export const FETCH_USER_SPOTIFY_PROFILE = "FETCH_USER_SPOTIFY_PROFILE";
export const FETCH_USER_FRIENDS = "FETCH_USER_FRIENDS";
export const FETCH_USER_TASTE = "FETCH_USER_TASTE";
export const FETCH_TRACK_INFOS = "FETCH_TRACK_INFOS";
export const FETCH_TOP_GENRES = "FETCH_TOP_GENRES";
export const FETCH_USER_TOP_ARTISTS = "FETCH_USER_TOP_ARTISTS";
export const FETCH_DECADE = "FETCH_DECADE";
export const FETCH_TRENDEX = "FETCH_TRENDEX";
export const STORE_TOKEN = "STORE_TOKEN";
export const STORE_SPOTIFY_TOKEN = "STORE_SPOTIFY_TOKEN";
export const SET_COMPARE = "SET_COMPARE";
export const STORE_USER = "STORE_USER";
export const ADD_FRIEND = "ADD_FRIEND";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const CLEAR_USERS = "CLEAR_USERS";


// new types
export const FETCH_MY_ID = "FETCH_MY_ID";
export const FETCH_MY_GROUPS = "FETCH_MY_GROUPS";
export const FETCH_USER_1 = "FETCH_USER_1";
export const FETCH_USER_2 = "FETCH_USER_2";