
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_USER_TASTE = "FETCH_USER_TASTE";
export const FETCH_TRACK_INFOS = "FETCH_TRACK_INFOS";
export const FETCH_TOP_GENRES = "FETCH_TOP_GENRES";
export const FETCH_DECADE = "FETCH_DECADE";
export const FETCH_POPULARITY = "FETCH_POPULARITY";

export const FETCH_TOKEN = "FETCH_TOKEN";
